# Generated by Django 5.0.2 on 2024-02-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-date_payments',), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
