# Generated by Django 5.0.2 on 2024-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid_method',
            field=models.CharField(blank=True, choices=[('наличными', 'Наличные'), ('перевод на счет', 'Перевод')], null=True, verbose_name='метод оплаты'),
        ),
    ]
