# Generated by Django 5.0.2 on 2024-02-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payments_paid_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_method',
            field=models.CharField(blank=True, choices=[('наличныe', 'Наличные'), ('перевод на счет', 'Перевод')], null=True, verbose_name='метод оплаты'),
        ),
    ]
