# Generated by Django 5.0.2 on 2024-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payments_payment_id_payments_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid_sum',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
