# Generated by Django 5.0.2 on 2024-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payments_paid_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payments',
            field=models.DateField(auto_now_add=True, verbose_name='дата платежа'),
        ),
    ]
