# Generated by Django 5.0.2 on 2024-03-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_subscription_course_alter_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
