# Generated by Django 5.0.2 on 2024-03-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='обновление'),
        ),
    ]
